### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by iamchriswick** [tim5go/linkedin-crawler#1]
Does this repo still work, and if so could you provide som instructions on how to use it?

**Comment by tim5go** [comment]
Hi @iamchriswick, this repo probably doesn't work anymore.
There're 2 reasons for that:
1) LinkedIn right now usually requires you to login in order to view the profile data. 
2) **phantomjs** is no longer supported, in particular, **phantomjs** doesn't work with most of the latest webdrivers
